config/routes.rb
Rails.application.routes.draw do
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
      put "unvote", to: "comments#unvote"
    end
  end
  
  resources :subs do
    collection do 
      get 'mySubscriptions'
    end
  end
  
  get 'subs/:id/subscribedusers' => "subs#subscribedusers"
  
  
  devise_for :users
 
  resources :subscriptions
  

  
  
  
  root 'subs#index'
  
   resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      put "unvote", to: "posts#unvote"
    end
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    
    acts_as_votable
    
    
    belongs_to :user, :foreign_key => "user_id"
    belongs_to :post, :foreign_key => "post_id"
    
    belongs_to :parent, :class_name  => "Comment", :foreign_key => "parent_comment_id"
    has_many :replies, :class_name => "Comment", :foreign_key => "parent_comment_id"  
    
    
    def score
        self.get_upvotes.size - self.get_downvotes.size
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  




  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = current_user.comments.build(comment_params)
    
    @post = Post.find(params[:post_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to request.referrer, notice: "Successfully create new comment"
    else
      render 'new'
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  
    def upvote
        @comment = Comment.find(params[:id])
        @comment.upvote_by current_user
        redirect_to request.referrer 
    end
    
    def downvote
        @comment = Comment.find(params[:id])
        @comment.downvote_by current_user
        redirect_to request.referrer
    end
    
    
    def unvote
        @comment = Comment.find(params[:id])
        @comment.unvote_by current_user
        redirect_to request.referrer
    end


















  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :content, :parent_comment_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :post_id, :value => @post.id, :readonly => 'true' %>
    <%= f.input_field :parent_comment_id %>

    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>User</th>
      <th>Post</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$('#comment-form').html("<%= j (render 'form') %>");
$('#comment-form').slideDown(350);

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @comment.id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @comment.parent_comment_id %>
</p>




<%= link_to "upvote", like_comment_path(@comment), method: :put %>
<%= link_to "downvote", dislike_comment_path(@comment), method: :put %>
<%= link_to "unvote", unvote_comment_path(@comment), method: :put %>

<%= @comment.score %>




<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>