config/routes.rb
Rails.application.routes.draw do
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
      put "unvote", to: "comments#unvote"
    end
  end
  
  resources :subs do
    collection do 
      get 'mySubscriptions'
    end
  end
  
  get 'subs/:id/subscribedusers' => "subs#subscribedusers"
  
  
  devise_for :users
 
  resources :subscriptions
  

  
  
  
  root 'subs#index'
  
   resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      put "unvote", to: "posts#unvote"
    end
  end
  
end

app/models/sub.rb
class Sub < ActiveRecord::Base
    belongs_to :user
    
    
    has_many :posts
    has_many :subscrptions
    has_many :users, :through => :subscrptions
    
   
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.all
  end


  def mySubscriptions
    @subs = current_user.subs  
  end




  # GET /subs/1
  # GET /subs/1.json
  def show
    @subscription = Subscription.new
  end

  def subscribedusers
    @user = Sub.find(params[:id]).users
  end
  


  # GET /subs/new
  def new
    @sub = current_user.subs.build
  end
  
  
  # GET /subs/1/edit
  def edit
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = current_user.subs.build(sub_params)

      if @sub.save
        redirect_to @sub, notice: 'Sub was successfully created.' 
        
      else
        render :new 
      end
    
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
   
      if @sub.update(sub_params)
         redirect_to @sub, notice: 'Sub was successfully updated.' 
      else
        render :edit 
      end
  end
  

  def destroy
    @sub.destroy
    redirect_to subs_url, notice: 'Sub was successfully destroyed.' 
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:title)
    end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<%= simple_form_for(@sub) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= sub.title %></td>
        <td><%= link_to 'Show', sub %></td>
        <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
        <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

app/views/subs/mySubscriptions.html.erb
<p id="notice"><%= notice %></p>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        

<h1>Listing your Subs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= sub.title %></td>
        <td><%= link_to 'Show', sub %></td>
        <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
        <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @sub.title %>
</p>


<h2><%= link_to 'New post', new_post_path(:sub_id => 1) %></h2>
<h2><%= link_to 'Subscribe', new_subscription_path(:sub_id => 1) %></h2>




<%= render :partial => '/subscriptions/form', :object => @subscription%>

<div>
  <% @sub.posts.each do |p|%>
    <%= p.title %>
    
  <% end %>
    
  
</div>



<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>