config/routes.rb
Rails.application.routes.draw do
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
      put "unvote", to: "comments#unvote"
    end
  end
  
  resources :subs do
    collection do 
      get 'mySubscriptions'
    end
  end
  
  get 'subs/:id/subscribedusers' => "subs#subscribedusers"
  
  
  devise_for :users
 
  resources :subscriptions
  

  
  
  
  root 'subs#index'
  
   resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
      put "unvote", to: "posts#unvote"
    end
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
    acts_as_votable
 
    
    belongs_to :user
    belongs_to :sub

    has_many :comments


    def score
        self.get_upvotes.size - self.get_downvotes.size
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]



    def index
        @posts = Post.all
        
    end
    
    def new
        @post = current_user.posts.build
        
        @sub = Sub.find(params[:sub_id])
    
    end
    
    
    
    def create
        @post = current_user.posts.build(post_params)
    
    
        if @post.save
            redirect_to @post, notice: "Successfully create new post"
        
        else
            render 'new'
        end
    end
    
    
    def show
        @comment = Comment.new
        gon.comments = @post.comments.each
    end
    
    def edit
    end
    
    def update
        if @post.update(post_params)
            redirect_to @post, notice: "Post was successfully updated"
        else
            render 'edit'
        end
    end
    
    
    
    def upvote
        @post = Post.find(params[:id])
        @post.upvote_by current_user
        redirect_to @post
    end
    
    def downvote
        @post = Post.find(params[:id])
        @post.downvote_by current_user
        redirect_to @post
    end
    
    
    def unvote
        @post = Post.find(params[:id])
        @post.unvote_by current_user
        redirect_to @post
    end
    
    
  
    
    def destroy
        @post.destroy
        redirect_to root_path
    end
    
    
    
    
    
    private
    
    def post_params
    
        params.require(:post).permit(:title,:sub_id)
    end
    

    def find_post
        @post = Post.find(params[:id])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id='errors'>
            
            <h2><%= pluralize(@post.errors.count, 'error') %>
            prevented this Pin from saving
            </h2>
            <ul>
                <% @post.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    
    <div class="form-group">
        <%= f.input :title, input_html: { class: 'form-group' } %>
        <%= f.hidden_field :sub_id, :value => @sub.id %>
    </div>
    
    <%= f.button :submit, class: 'btn btn-primary'%>


<% end %>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= render 'form'%>

<%= link_to 'Cancel',  post_path %>

app/views/posts/index.html.erb
<h1>Index</h1>

<h3><%= link_to 'New post', new_post_path%></h2>



<% @posts.each do |post| %>
    <%= link_to post.title, post%></br>
    
<% end %>

app/views/posts/new.html.erb
<h1>New form</h1>


<%= render 'form' %>

<%= link_to 'Back',  root_path %>

app/views/posts/show.html.erb
<h1>Post</h1>


<%= @post.title%>
<p><%= @post.user.email %></p>


<button id='comment'>Create comment</button>


<div style="display:none;" id='text'><%= render :partial => '/comments/form', :object => @comment%></div>
    

<h1>Comments</h1>
</br>

<% @post.comments.each do |c|%>
    <% if c.parent_comment_id == nil%>
        <div style='border: 1px solid black' id = "<%=c.id%>"><%=c.content %>
        <button class='reply'>Reply</button></div>
    <%end %>
    <% end %>


    
    
    
    
    
    
    
    

<%= link_to 'Back', root_path %>
<%= link_to 'Edit',  edit_post_path %>


<%= link_to "upvote", like_post_path(@post), method: :put %>
<%= link_to "downvote", dislike_post_path(@post), method: :put %>
<%= link_to "unvote", unvote_post_path(@post), method: :put %>


<%= @post.score %>

<%= link_to 'Delete',  post_path, method: :delete, data: {confirm: "Are you sure?"} %>